#!/bin/bash
DOTOOL_COMMAND="sudo dotoolc"
MIN_DELAY=""
MAX_DELAY=""
ACTION=""
BUTTON_IN=""
while getopts "p:r:c:m:M:" opt; do
  case "$opt" in
    p)
      if [ -n "$ACTION" ]; then exit 1; fi
      ACTION="press"
      BUTTON_IN="$OPTARG"
      ;;
    r)
      if [ -n "$ACTION" ]; then exit 1; fi
      ACTION="release"
      BUTTON_IN="$OPTARG"
      ;;
    c)
      if [ -n "$ACTION" ]; then exit 1; fi
      ACTION="click"
      BUTTON_IN="$OPTARG"
      ;;
    m)
      MIN_DELAY="$OPTARG"
      ;;
    M)
      MAX_DELAY="$OPTARG"
      ;;
    \?)
      exit 1
      ;;
  esac
done
if [ -z "$ACTION" ] || [ -z "$BUTTON_IN" ]; then
    exit 1
fi
if [ "$ACTION" = "click" ]; then
    if [ -z "$MIN_DELAY" ] || [ -z "$MAX_DELAY" ]; then
        exit 1
    fi
    if (( $(echo "$MIN_DELAY >= $MAX_DELAY" | bc -l) )); then
        exit 1
    fi
fi
BUTTON_OUT=""
case "$BUTTON_IN" in
    1)
        BUTTON_OUT="1"
        ;;
    2)
        BUTTON_OUT="3"
        ;;
    3)
        BUTTON_OUT="2"
        ;;
    *)
        exit 1
        ;;
esac
if [ "$ACTION" = "press" ]; then
    echo "buttondown $BUTTON_OUT" | $DOTOOL_COMMAND
elif [ "$ACTION" = "release" ]; then
    echo "buttonup $BUTTON_OUT" | $DOTOOL_COMMAND
elif [ "$ACTION" = "click" ]; then
    CLICK_DURATION=$(awk -v min="$MIN_DELAY" -v max="$MAX_DELAY" -v seed="$(date +%s%N)" '
    BEGIN{
        srand(seed);
        print min + rand() * (max - min)
    }')
    echo "buttondown $BUTTON_OUT" | $DOTOOL_COMMAND
    sleep "$CLICK_DURATION"
    echo "buttonup $BUTTON_OUT" | $DOTOOL_COMMAND
fi
